# NB: don't set `language: haskell` here

env:
 - CABALVER=1.20 GHCVER=7.8.4  ALEXVER=3.1.3 HAPPYVER=1.19.3
 - CABALVER=1.22 GHCVER=7.10.1 ALEXVER=3.1.4 HAPPYVER=1.19.5
 - CABALVER=1.22 GHCVER=7.10.2 ALEXVER=3.1.4 HAPPYVER=1.19.5
 - CABALVER=head GHCVER=head   ALEXVER=3.1.4 HAPPYVER=1.19.5

matrix:
 allow_failures:
  - env: CABALVER=1.22 GHCVER=7.10.2 ALEXVER=3.1.4 HAPPYVER=1.19.5
  - env: CABALVER=head GHCVER=head   ALEXVER=3.1.4 HAPPYVER=1.19.5

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy-$HAPPYVER alex-$ALEXVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install -j --only-dependencies --enable-tests

script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal configure -v2 --enable-tests
 - cabal install -j1 --enable-tests
 - cabal test --show-details=streaming
 - cabal check
 - cabal sdist
